# Generated by Django 6.1.1 on 2026-09-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('author', models.CharField(max_length=150, verbose_name='Автор')),
                ('genre', models.CharField(max_length=100, verbose_name='Жанр')),
                ('description', models.TextField(verbose_name='Описание')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='books/', verbose_name='Обложка')),
                ('avidreaders_url', models.URLField(blank=True, verbose_name='Ссылка на AvidReaders')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['-created_at'],
            },
        ),
    ]
